### ISSUE TITLE
Undeclared dependency to criterium

### ISSUE THREAD

**Issue by foobar27** [mschuene/stratege#1]
When I add the dependency `[stratege "0.1.0"]` I also need to add the dependency to `[criterium "0.4.3"]`, else I cannot require `[stratege.core :as s :refer [rules]]` due to missing `criterium.core`.
Maybe criterium could be a development-dependency, and not required at all in production code?

**Comment by mschuene** [comment]
I moved criterium to dev-dependencies before releasing, but forgot to remove the (unused) require clause for it from stratege.core ...
I pushed stratege 0.1.1 that fixes this.
