### ISSUE TITLE
How to write recursive strategies for arbitrary length predicates?

### ISSUE THREAD

**Issue by jeroenvandijk** [mschuene/stratege#3]
Hi Maik,

Thank you for publishing this library. I'm trying to use it to create a generic dnf term rewriter. I'm not yet able to create recursive rules that match predicates of arbitrary lengths.

Simple predicates work:

``` clojure
[:not [:or a b]] ;=> [:and [:not a] [:not b]]
```

But how do I write rules that are recursive and will match predicates of arbitrary lengths, like:

``` clojure
[:not [:or a b c]] ;=> [:and [:not :a] [:not :b] [:not c]]
[:not [:or a b c d]] ;=> [:and [:not :a] [:not :b] [:not c] [:not d]]
[:not [:or a b c d e]] ;=> [:and [:not :a] [:not :b] [:not c] [:not d] [:not e]]
;; etc
```

Thanks,
Jeroen

**Comment by jeroenvandijk** [comment]
I have been hacking a bit and this seems to work so far: https://gist.github.com/jeroenvandijk/337bae7cc7d920dd6975f840a0c920ba

**Comment by mschuene** [comment]
Hi Jeroen,

The rules macro is just a shorthand to make a core.match on the current node and replace it with the matching right hand side. That means, you can use arbitrary clojure code in the rule clauses. 
See the following for variable length dnf forms.

``` clojure
(def arbitrary-lenght-rules 
                 (rules
                  (rule [:not [:or & x]] -> (apply conj [:and] (map (fn [v] [:not v]) x)))
                  (rule [:not [:not x]] -> x)))

((innermost arbitrary-lenght-rules) [:not [:or 1 [:not 2]]])
;=> [:and [:not 1] 2]

```

**Comment by jeroenvandijk** [comment]
Hi Maik,

Thanks for the suggestion. I've applied core.match tricks to get the dnf rewriter working (`test.check` says it works<sup>TM</sup>). See https://gist.github.com/jeroenvandijk/337bae7cc7d920dd6975f840a0c920ba

I'm quite sure the rules can be optimized more. Do you think the Stratege/StrategoXT approach is an efficient way to approach the DNF rewriting problem? Either way thanks for you help.
